name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}-arch-mingw-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-arch-mingw-

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm --needed git make mingw-w64-gcc

      - name: Compile
        run: |
          make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: d3d9-dll
          path: d3d9.dll

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: d3d9.dll
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
